---
title: "Measuring air quality"
editor: 
  markdown: 
    wrap: 72
---

An example of a second page on the site, to demo the nav bar

Air quality monitoring in B.C. is conducted by the provincial government, Metro Vancouver, and industry (where required by permit) in cooperation with Environment Canada and regional districts.

The province uses a number of methods to measure and monitor air quality, including permanent monitoring stations in communities, mobile instrumentation (e.g. on a truck or airplane), and industrial stack monitoring.

There are approximately 150 air quality monitoring stations (100 continuous, 50 non-continuous) throughout B.C. Metro Vancouver air quality staff operate approximately 20 of these continuous stations. The 80 continuous stations in the remainder of the province are run and maintained by a combination of Ministry of Environment (MOE) and industry (permittee) staff.

In addition, there are approximately 20 industrial facilities across the province that continuously monitor air pollutants that are emitted directly from their facilities (i.e. in the stacks). There are a further 80 industrial facilities that perform yearly or quarterly sampling on emissions from their stacks, as required by their permit to operate.

## How we collect & measure data

Monitoring stations measure the presence of contaminants in the air, such as carbon monoxide (CO), nitrogen dioxide (NO2), ozone (O3), particulate matter (PM2.5 and PM10), sulphur dioxide (SO2), and hydrogen sulphide (H2S). The data are reported as raw parameters, and are also used to calculate the Air Quality Health Index.

Contaminants are measured in one of three ways: continuous monitoring (real-time, automated), non-continuous monitoring (discrete, manual) or mobile monitors.

<details>
<summary>Continuous Monitoring (automated)</summary>

In continuous monitoring, air quality is constantly measured by drawing air in through various tubes that are connected to data loggers that automatically transmit the data to a central MOE database. The data is automatically checked for errors and is published hourly on the Current Air Data page, where it is available to the public, and used to calculate the Air Quality Health Index (AQHI).

This data is useful for providing real-time information and for calculating indexes. However, until it goes through the MOE's data validation process, it is still considered raw data and should not be used for comparing to air quality guidelines or objectives.

The province uses a wide range of automated instruments to collect and measure air quality data, including the following (with instrument acronyms and parameters measured in parenthesis):

-   Tempered Element Oscillating Microbalance (TEOM) (PM2.5 and PM10)
-   Beta AttenuatedMonitoring (BAM) (PM2.5)
-   UV Photometry (ozone)
-   Chemiluminscence (nitrogen dioxide)
-   UV Fluorescence (sulphur dioxide)
-   Nondispersive Infrared Photometry (carbon monoxide)
-   Pulsed Fluorescence (total reduced sulphur or H2S)
</details>

<details>
<summary>Non-Continuous Monitoring (manual)</summary>
Manual sampling is preferred in some cases because it is easier and less expensive than continuous, automatic sampling, while producing equally valuable results.

Manual sampling is performed by Ministry staff and by industry and institutions that are required to conduct air quality sampling as a condition of their operation (permittees). The sampling must follow strict and comprehensive guidelines set out by the Ministry of Environment.

In manual sampling, filters or canisters are placed in the field by technicians for a discrete period of time (such as one, three, or six days), and then a technician collects the filter or canister and sends it to a certified laboratory where they are weighed and analyzed to determine their content. The laboratory then uploads the data to a central Ministry of Environment database.

The Ministry uses a range of manual instruments to collect and measure air quality data, including the following:

- Single Channel 16.7l/m (PM2.5 and PM10) monitors
- Dichotomous (Coarse and Fine PM) monitors
- Speciation monitors
- Volatile Organic Compound monitors (VOCs)
- PAH monitors
- Passive samplers
</details>

<details>
<summary>Mobile Monitors</summary>
Mobile monitors consist of a number of instruments installed in a large vehicle or an airplane, and are used to assess ambient air quality over short periods of time in areas not covered by the permanent monitoring network, or for special studies.

There are mobile air quality monitors in Metro Vancouver and in the rest of the province, such as the Ministry’s Mobile Air Monitoring Laboratory (MAML) and the speciation monitor. The MAML can monitor meteorological conditions, and take continuous and non-continuous measurements for a variety of parameters. Speciation monitors collect data by taking integrated samples over a 24-hour period from ambient air. These samples are analysed by a lab for a suite of chemical components and are used as part of receptor modelling.
</details>

## How Instruments are Calibrated & Maintained
The Ministry of Environment has adopted Environment Canada's Standard Operating Procedures (SOPs) for instrument calibration and maintenance.

Technicians visit stations monthly and perform checks to ensure the equipment is working properly. The technicians are responsible for reporting any major instrument problems to Ministry staff. If an instrument is cited as having problems, then the data is flagged as suspicious. In addition, the provincial audit team performs twice-yearly audits on the stations to ensure that all equipment is working properly.

Further guidelines on manual and automated monitoring can also be found in the B.C. Field Sampling Manual.

## How We Analyze & Use Data
For proper air quality assessment, one needs validated data. This requires human review and analysis. This is done by the Ministry of Environment's air data validation team and is typically a three-month process before the data is archived as valid data.

Non-continuous data also goes through a validation process and is then stored in the Ministry of Environment's Environmental Monitoring System (EMS). This data is available to registered ministry staff, B.C. health authorities and Qualified Environmental Professionals through the Environmental Monitoring System Web Reporting (EMS WR). This data is also available upon request.The Ministry of Environment houses validated air quality data going back to 1979.

This data provides a basis for in-depth analyses and reporting of air quality trends in British Columbia, including emissions inventories and modelling. The reports and publications section includes reports on a number of air quality issues and trends.

Continuous and non-continuous data are housed in a central data warehouse of the Ministry of Environment where they are screened by data validation technicians for errors. Once the data has been certified as correct (i.e., validated), the data can then be used for reporting out to the public, comparing with objectives and guidelines, regulatory purposes, and by scientists for more detailed analysis.

Twice a year, the Ministry of Environment's air audit team audits every air quality monitoring station in B.C. that falls under provincial jurisdiction. This includes both ministry-operated sites and monitoring stations that are regulated under industry permits, such as continuous emissions monitors for industrial stacks and ambient air monitors. Refer to the Auditing factsheet (PDF) for additional information.