name: Deploy to GitHub Pages On PR

on:
  push:
    branches:
      - main

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        working-directory: air-quality-statements
        shell: "bash"
        run: npm install
      - name: Build
        shell: "bash"
        working-directory: air-quality-statements
        run: |
          export BASE_URL="/nr-aqadvisories-temp/"
          npm run build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "air-quality-statements/dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
